### ISSUE TITLE
AttributeError: TranscriptionMatrix instance has no attribute 'gene_list'

### ISSUE THREAD

**Issue by Shenglai** [hakyimlab/Training#2]
Hi all,

I'm trying to run PrediXcan (master branch, commit 8bca77417e33b74d3233b1598969a953a882dc42)with 3615 TCGA samples on both TW_Lung_0.5.db and TW_Breast_Mammary_Tissue_0.5.db.
However, I got an error saying 
```Traceback (most recent call last):
  File "/mnt/SCRATCH/PrediXcan/Software/PrediXcan.py", line 214, in <module>
    main()
  File "/mnt/SCRATCH/PrediXcan/Software/PrediXcan.py", line 197, in main
    transcription_matrix.save(PRED_EXP_FILE)
  File "/mnt/SCRATCH/PrediXcan/Software/PrediXcan.py", line 117, in save
    outfile.write('FID\t' + 'IID\t' + '\t'.join(self.gene_list) + '\n') # Nb. this lists the names of rows, not of columns
AttributeError: TranscriptionMatrix instance has no attribute 'gene_list'
```
I've tried run PrediXcan with and without `--genelist` flag, but neither worked. The exact cmd I used is :
```
/path/to/PrediXcan.py --predict --dosages /path/to/dosage/ --dosages_prefix chr --samples tcga.impute2.fam --weights /path/to/TW_Breast_Mammary_Tissue_0.5.db --output_dir tcga_3615_brca_gtex_model (--genelist /path/to/gene_breast.txt) #The gene_breast.txt is actually #1 column from TW_Breast_Mammary_Tissue_0.5.txt
```
Please let me know if more information is required. Thank you so much! 
It is the same issue as https://github.com/hakyim/PrediXcan/issues/19, and also very similar to https://github.com/hakyimlab/Training/issues/1

**Comment by ScottPDickinson** [comment]
This probably isn't an issue with the --genelist flag. If you are using all genes in the prediction database, you can leave the flag out.

Can you double check two things? First, make sure the path to you genotype dosages is correct.  Then, see if the rsids that are in your files are used in the prediction database. The error you're getting might happen if none of your snps are in the database.

**Comment by Shenglai** [comment]
Thank you so much for the prompt reply!
The path to genotype dosages is correct.
However, I checked a few lines and did find the differences:
```
chr22 rs150457414:16225632:G:A 16225632 G A 0.02845 0 0.0569 0.0569 0 0.0569 0.0569 0 0 0 0 0 0 0
```
```
chr22 rs2236636 16464422 C A 0.515366430260047 1 1 2 1 1 0 1 1 2 2 0 0 1 1
```
The first line is from my genotype dosage file, which is converted from plink by https://github.com/hakyim/PrediXcan/blob/master/Software/convert_plink_to_dosage.py. 
The second line is from the PrediXcan Example tar file, https://s3.amazonaws.com/imlab-open/Data/PredictDB/PrediXcanExample.tar.
It seems the second column has an incorrect format from example, and I'm wondering if this is causing the error.
The further question is how to properly prepare the rsid in my case?
It seems to me that I could just use `awk '{FS=":"}{print $1}'` to get the first part of my second column as the rsid.
However, I've seen some lines:
```
ubuntu@fan-vm-es1:/mnt/SCRATCH/dosage$ zcat chr22.tcga_3615_dosage.txt.gz | awk '{print $2}' | head -n 7
rs202125193:16060513:T:C
rs200287973:16060515:C:T
rs9604663:16060517:T:C
rs143164330:16060567:T:G
rs201278103:16081207:G:A
rs1988024:16113892:T:C
22:16149693:C:T
```
The last line shows `22:16149693:C:T`, which might suggest `chr22 (empty rsid) 16149693 C T`. For cases like this, is it fine if I leave `22` as rsid or should I remove lines w/o rsid?
Thank you so much!

**Comment by ScottPDickinson** [comment]
Yes, the format is causing the error. I'd recommend replacing the ':' character in each dosage file with a single space character or a tab.  You should be able to use sed or awk to do that.

You can leave lines w/o rsids in, because the software will just skip the line.  Right now the software is skipping all lines because it's unable to match any of the rsids exactly.

**Comment by Shenglai** [comment]
@ScottPDickinson I just replaced the whole 2nd column from my dosage files to rsid, because I'm concerning that it would duplicate the `position`, `allele1` and `allele2`. And it's working now. Thank you so much for the help!
