### ISSUE TITLE
Run Error - 

### ISSUE THREAD

**Issue by ghost** [hakyimlab/Training#3]
Dear Community,

When I run the following command,

python PrediXcan.py --predict --assoc --linear --genelist genelist.txt --dosages ~/Working/GWAs1_dosage_controls/ --dosages_prefix GWAs1_CasControls_chr --samples GWAs1_contrls_sample.txt --pheno GWAs1_cntrls_Pheno_Status_Age_Sex_4PCA1.txt --weights Working/ModelPrediction/DGN-HapMap-2015/DGN-WB_0.5.db --output_prefix GWAs1_controls_DGN-WB_0.5

It gives me the following error:
2017-07-04 15:49:22.244233 Preloading weights...
2017-07-04 15:49:23.198338 Processing GWAs1_CasControls_chr1.extracted.dose_controls.geno.gz
2017-07-04 15:49:25.538974 Processing GWAs1_CasControls_chr22.extracted.dose_controls.geno.gz
Traceback (most recent call last):
  File "PrediXcan.py", line 230, in <module>
    main()
  File "PrediXcan.py", line 211, in main
    transcription_matrix.update(gene, weight, ref_allele, allele, dosage_row)
  File "PrediXcan.py", line 104, in update
    self.D[self.gene_index[gene],] += dosage_row * weight
ValueError: operands could not be broadcast together with shapes (1228,) (411,) (1228,)

But if I change the model database, it runs fine, for example:

python PrediXcan.py --predict --assoc --linear --genelist genelist.txt --dosages ~/Working/GWAs1_dosage_controls/ --dosages_prefix GWAs1_CasControls_chr --samples GWAs1_contrls_sample.txt --pheno GWAs1_cntrls_Pheno_Status_Age_Sex_4PCA1.txt --weights Working/ModelPrediction/GTEx_TW_Artery_Tibial.db --output_prefix GWAs1_controls_TW_Artery_Tibial

The above command run perfectly fine.

I want to know why my above command is not successful? Is this database problem? But the same DGN database runs fine with other data as well but not with this one.

Thanks,

Waqas.

**Comment by hakyim** [comment]
I just realized that you posted this issue. Hopefully, it was resolved. If you have further questions please email predixcanmetaxcan@googlegroups.com
