### ISSUE TITLE
AttributeError: TranscriptionMatrix instance has no attribute 'gene_list'

### ISSUE THREAD

**Issue by yunjuyang** [hakyimlab/Training#4]
I am trying to run PrediXcan to get predited transcription levels for my data.
Below is the code. 
/PrediXcan.py --predict --dosages /home/yjyang/OFC/StudyData/GenotypeFiles/New_Impute/dosage \
 --dosages_prefix cleft.chr \
--samples sample.txt \
--weights /home/yjyang/OFC/PrediXcan/GTEx-V6p-HapMap-2016-09-08/TW_Whole_Blood_0.5.db  \
--output_prefix /home/yjyang/OFC/PrediXcan/Output/WB

And I keep getting the below error. 
2017-12-14 16:12:06.884132 Preloading weights...
Traceback (most recent call last):
  File "PrediXcan.py", line 230, in <module>
    main()
  File "PrediXcan.py", line 212, in main
    transcription_matrix.save(PRED_EXP_FILE)
  File "PrediXcan.py", line 117, in save
    outfile.write('FID\t' + 'IID\t' + '\t'.join(self.gene_list) + '\n') # Nb. this lists the names of rows, not of columns
AttributeError: TranscriptionMatrix instance has no attribute 'gene_list'

How can I fix this issue?

I found the same issue so I checked the path of dosage files and contents of the files, but they are correct.

**Comment by hakyim** [comment]
Dear Yunjunyang, I just realized that you posted this issue. Hopefully, it was resolved. If you have further questions please email predixcanmetaxcan@googlegroups.com
